[project]
authors = ["Carlotta Sartore <carlotta.sartore@iit.it>"]
channels = ["conda-forge"]
description = "Suite of parametrized controller with simulation environments for co-design of Humanoid Robots"
name = "comodo"
platforms = ["linux-64"]
version = "0.0.0"
repository = "https://github.com/ami-iit/comodo"
readme = "README.md"
license-file = "LICENSE"

[dependencies]
adam-robotics = "*"
idyntree = "*"
bipedal-locomotion-framework = "*"
mujoco = "*"
mujoco-python-viewer = "*"
matplotlib = "*"
urllib3 = "*"
urchin = "*"
resolve-robotics-uri-py = "*"
notebook = "*"
rod = "*"
ipykernel = "*"
mesalib = "*"
optuna = ">=4.0.0,<5"
# jaxsim = ">=0.4.2"

[pypi-dependencies]
jaxsim = { git = "https://github.com/ami-iit/jaxsim.git", rev="visco_elastic_contacts", extras = ["all"]}
urdfmodifiers = { git = "https://github.com/CarlottaSartore/urdf-modifiers.git", rev="scalar_modification"}
comodo ={ path = "./", editable = true}
